# Alacritty Configuration

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.9

[font]
size = 11.0

[font.normal]
family = "SFMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SFMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SFMono Nerd Font Mono"
style = "Italic"

[cursor]
style.shape = "Block"
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
