# Alacritty Configuration

[general]
import = ["./colors.toml"]

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 0.9

[font]
size = 11.25

[font.normal]
family = "SFMono Nerd Font Mono"

[scrolling]
multiplier = 6

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true
