# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0C1523"
foreground = "#B1A9AB"

[colors.normal]
black   = "#3B3737"
red     = "#524145"
green   = "#586F93"
yellow  = "#A66A75"
blue    = "#F43F1F"
magenta = "#859BB1"
cyan    = "#E5CAC8"
white   = "#867C7E"

[colors.bright]
black   = "#5E5758"
red     = "#524145"
green   = "#586F93"
yellow  = "#A66A75"
blue    = "#F43F1F"
magenta = "#859BB1"
cyan    = "#E5CAC8"
white   = "#867C7E"
