# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0C0D0F"
foreground = "#AAADB5"

[colors.normal]
black   = "#3B3327"
red     = "#434B5B"
green   = "#595C62"
yellow  = "#6E6C69"
blue    = "#857E70"
magenta = "#907C5D"
cyan    = "#BC9C63"
white   = "#7D828D"

[colors.bright]
black   = "#585B62"
red     = "#434B5B"
green   = "#595C62"
yellow  = "#6E6C69"
blue    = "#857E70"
magenta = "#907C5D"
cyan    = "#BC9C63"
white   = "#7D828D"
