# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0B0C10"
foreground = "#B3B3B9"

[colors.normal]
black   = "#494741"
red     = "#575864"
green   = "#80798B"
yellow  = "#97BDA8"
blue    = "#F5B09D"
magenta = "#CCC9D4"
cyan    = "#F0E2BD"
white   = "#8A8B93"

[colors.bright]
black   = "#616167"
red     = "#575864"
green   = "#80798B"
yellow  = "#97BDA8"
blue    = "#F5B09D"
magenta = "#CCC9D4"
cyan    = "#F0E2BD"
white   = "#8A8B93"
