# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0E0F13"
foreground = "#B6B8BC"

[colors.normal]
black   = "#3F3833"
red     = "#5D626B"
green   = "#94787D"
yellow  = "#788296"
blue    = "#BB5F69"
magenta = "#8E7E7F"
cyan    = "#8091AB"
white   = "#8E9197"

[colors.bright]
black   = "#63666A"
red     = "#5D626B"
green   = "#94787D"
yellow  = "#788296"
blue    = "#BB5F69"
magenta = "#8E7E7F"
cyan    = "#8091AB"
white   = "#8E9197"
