# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0E0F13"
foreground = "#B6B8BC"

[colors.normal]
black   = "#3E3931"
red     = "#5D626B"
green   = "#A26D77"
yellow  = "#677AB5"
blue    = "#8AC3CF"
magenta = "#CEBDD2"
cyan    = "#E9CF9D"
white   = "#8E9197"

[colors.bright]
black   = "#63666A"
red     = "#5D626B"
green   = "#A26D77"
yellow  = "#677AB5"
blue    = "#8AC3CF"
magenta = "#CEBDD2"
cyan    = "#E9CF9D"
white   = "#8E9197"
