# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#07070A"
foreground = "#ADADB2"

[colors.normal]
black   = "#3F4039"
red     = "#4B4B54"
green   = "#787B8E"
yellow  = "#818D7E"
blue    = "#A7A2C9"
magenta = "#E8C3B4"
cyan    = "#D7DEB2"
white   = "#828288"

[colors.bright]
black   = "#5B5B5F"
red     = "#4B4B54"
green   = "#787B8E"
yellow  = "#818D7E"
blue    = "#A7A2C9"
magenta = "#E8C3B4"
cyan    = "#D7DEB2"
white   = "#828288"
