# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Set the format of the prompt
format = """
[](#3A3A3A)\
$os\
$username\
[](bg:#7A8D8D fg:#3A3A3A)\
$directory\
[](fg:#4E4E4E bg:#C7B095)\
$git_branch\
$git_status\
[](fg:#0096BE bg:#1c1f27)\
$time\
[ ](fg:#2A2A2A)\
$line_break\
$python\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$c\
$docker_context\
$character"""

# Disable the package module to avoid slowdown
[package]
disabled = true

[os]
style = "bg:#717687 fg:#e2e0d6"
disabled = false

[username]
show_always = true
style_user = "bg:#717687 fg:#e2e0d6"
style_root = "bg:#717687 fg:#FF0000"
format = '[$user ]($style)'

[directory]
style = "bg:#7A8D8D fg:#e2e0d6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
".config" = " "
"~" = " "

[git_branch]
symbol = " "
style = "bg:#C7B095 fg:#e2e0d6"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#C7B095 fg:#e2e0d6"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "󰕚 "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = " "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[time]
disabled = false
time_format = "%R" # Hour:Minute format
style = "bg:#1c1f27 fg:#e2e0d6"
format = '[ $time ]($style)'

# Programming languages
[python]
symbol = " "
style = "fg:#3776AB"
format = '[$symbol($version) ]($style)'

[rust]
symbol = " "
style = "fg:#DEA584"
format = '[$symbol($version) ]($style)'

[golang]
symbol = " "
style = "fg:#00ADD8"
format = '[$symbol($version) ]($style)'

[nodejs]
symbol = " "
style = "fg:#43853D"
format = '[$symbol($version) ]($style)'

[php]
symbol = " "
style = "fg:#777BB4"
format = '[$symbol($version) ]($style)'

[java]
symbol = " "
style = "fg:#007396"
format = '[$symbol($version) ]($style)'

[kotlin]
symbol = " "
style = "fg:#F88909"
format = '[$symbol($version) ]($style)'

[c]
symbol = " "
style = "fg:#A8B9CC"
format = '[$symbol($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#2496ED"
format = '[$symbol$context ]($style)'
