# : Manager [[[

[manager]
cwd = { fg = "#e8e1dd" }

# Tab
tab_active = { fg = "#3b2e1d", bg = "#d9c3ab", bold = true }
tab_inactive = { fg = "#f6dfc6", bg = "#25190a" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#f5af5c", bg = "#f5af5c" }
marker_cut = { fg = "#fbdebc", bg = "#fbdebc" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#dec2a2", bg = "#dec2a2" }

# Count
count_copied = { fg = "#271905", bg = "#fbdebc" }
count_cut = { fg = "#271905", bg = "#fbdebc" }
count_selected = { fg = "#3b2e1d", bg = "#dec2a2" }

# Border
border_symbol = "│"
border_style  = { fg = "#d9c3ab" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#3b2e1d", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#d9c3ab", fg = "#3b2e1d", bold = true }
normal_alt  = { bg = "#4a4643", fg = "#cbc5c1" }

# Select mode
select_main = { bg = "#d3c4b4", fg = "#382f24", bold = true }
select_alt  = { bg = "#4a4643", fg = "#cbc5c1" }

# Unset mode
unset_main = { bg = "#dec2a2", fg = "#3e2d16", bold = true }
unset_alt  = { bg = "#4a4643", fg = "#cbc5c1" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#d9c3ab", bg = "#3c3936" }
progress_error = { fg = "#ffb4ab", bg = "#3c3936" }

# Permissions
permissions_t = { fg = "#967858" }
permissions_w = { fg = "#ab773c" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#f2972c" }
permissions_s = { fg = "#e19542" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#d9c3ab" }
active = { fg = "#dec2a2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#d9c3ab" }
value = { fg = "#e8e1dd" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#d9c3ab", bg = "#3b2e1d" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#d9c3ab" }
title = {}
hovered = { fg = "#fbdebc", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c3936" }
cand = { fg = "#d9c3ab" }
rest = { fg = "#3b2e1d" }
desc = { fg = "#e8e1dd" }
separator = " ▶ "
separator_style = { fg = "#e8e1dd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e8e1dd" }
run = { fg = "#e8e1dd" }
footer = { fg = "#382f24", bg = "#d3c4b4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#dec2a2" }
title_warn = { fg = "#d9c3ab" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e8e1dd" },
    { name = "*/", fg = "#d9c3ab" },
]

# : ]]]